language: julia
os:
    - linux
julia:
    - 1.0
branches:
  only:
    - master
after_success:
  - julia --project=test/coverage -e 'using Pkg; Pkg.instantiate(); Pkg.add("Coverage")';
  - julia --project=test/coverage -e 'using Coverage; Codecov.submit(Codecov.process_folder())';
jobs:
  include:
    - stage: "Documentation"
      julia: 1.0
      os: linux
      script:
        - julia --project=docs -e 'using Pkg; Pkg.instantiate(); Pkg.add(PackageSpec(path=pwd()))'
        - julia --project=docs --color=yes docs/make.jl
